### ISSUE TITLE
Searching/sorting on eager loaded models

### ISSUE THREAD

**Issue by ikerasLT** [yajra/laravel-datatables#366] opened 2016-01-29 17:39 UTC
Is this going to be supported in near future?

**Comment by yajra** [comment] 2016-01-30 05:21
YES, but the problem is I don't have any idea yet how to implement it. ^_^

If you some solutions in mind, please do not hesitate to submit a PR. Thanks!

**Comment by ikerasLT** [comment] 2016-02-04 17:49
Ok, found the solution for global search. No ordering though

**Comment by yajra** [comment] 2016-02-10 03:07
Your PR #381 merged and [demo](http://datatables.yajrabox.com/eloquent/relationships) were updated to reflect the changes. Thanks!

**Closed by yajra** 2016-02-10 03:07 UTC

**Comment by ikerasLT** [comment] 2016-02-10 15:44
No problem, will try to implement sorting when I have time
