### ISSUE TITLE
[Bug] Laravel randomly logs out the user

### ISSUE THREAD

**Issue by javenosa** [yajra/laravel-datatables#60] opened 2015-05-21 19:52 UTC
I make a simple example with the bundle (version 5).
Everything works fantastic until I press more than once any column to order by the data.

The method need authorization. So I need to be logged in the site, but when the problem occur the user are automatically logged out.

There is a chance to fix this?

**Comment by yajra** [comment] 2015-05-22 02:41
hi @javenosa , this is a weird bug and can't replicate it. A duplicate issue can be found in #19. Can you please try the suggestions there and check if it works?

**Comment by yajra** [comment] 2015-05-22 03:03
I've googled this and it seems like a Laravel Bug or something. Here's some link as reference:

- http://www.tech.theplayhub.com/laravel_-_logging_out_randomly/
- http://stackoverflow.com/questions/24053235/laravel-auth-session-losing-when-redirect-pages
- https://laravel.io/forum/05-15-2015-user-randomly-getting-logged-out

Tagging guys on #19. @wessodesigner @illuminate3

**Comment by javenosa** [comment] 2015-05-26 13:18
Mmmm complicated.

I just change the code as the 19 issue. My request now works with POST and doesn't have any problem.

This information can give you the basic idea of the bug. I would try to look in the component of the request, because on the post the cookies send across the headers. This can be a problem on the GET request.

Another thing is the database, I use postgresql.
There is no problem with the count of data because I only have 1 register on my DB. 
So don't worry about the weight of the result.

**Comment by asasmoyo** [comment] 2015-05-29 01:02
i also changed my request to post and it is works now

**Comment by yajra** [comment] 2015-06-10 08:50
Therefore, the fix for this intermittent bug is by using a **POST** method on DataTables. Thanks for the feedbacks!

**Closed by yajra** 2015-06-10 08:50 UTC

**Comment by yajra** [comment] 2015-09-15 08:37
@javenosa, @asasmoyo  are you using "artisan serve"? #167 seems to prove that this issue was due to it. Feedback much appreciated. Thanks!

**Comment by javenosa** [comment] 2015-09-15 22:53
@yajra Yes, I was using the local server "artisan server" over php.

That was the problem? 
Why?

**Comment by yajra** [comment] 2015-09-16 00:40
As per user's comment:
>mgsmus commented on Sep 16, 2014
I've had this problem. I was using PHP's built in web server via "artisan serve". I switched to Apache and the problem is solved. I guess the reason is multi-threading that built-in server doesn't support.

Thanks for confirming. This ghost bug is finally revealing itself via "artisan serve".

**Comment by mrofi** [comment] 2015-09-16 00:45
I switched to apache from "artisan serve". it fix my problem..

**Comment by javenosa** [comment] 2015-09-16 04:36
@yajra Good news!
