### ISSUE TITLE
Adding a column named 'delete' results in unexpected behaviour/errors/potential data loss

### ISSUE THREAD

**Issue by ctoma** [yajra/laravel-datatables#640] opened 2016-07-13 16:50 UTC
Hi,

I'm using laravel 5.1.40. I recently upgraded from v6.10.1 to v6.15.1. This was actually a breaking change on one of my pages. To give some context I am fetching a list of users. Some of the columns I am editing and one of the columns I add is a 'delete' column which has a simple delete button.

The error is: ```SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`[REDACTED]`.`[REDACTED]`, CONSTRAINT `[REDACTED]user_id_foreign` FOREIGN KEY (`[REDACTED]user_id`) REFERENCES `users` (`id`)) (SQL: delete from `users` where `id` = 113)```

The interesting thing about this is that it's trying to delete the first user in the result set. This should **never** happen, and I was lucky that a foreign key was stopping this from happening. This can potentially result in data loss for people just by upgrading their laravel-datatables package.

My query looks roughly like this (I have removed irrelevant parts):
```php
$users = User::select('users.id', 'users.email','users.last_login', 'users.name');
$datatables = app('datatables')->of($users);
$datatables->editColumn('name', 'HIDDEN');
$datatables->addColumn('delete', function ($user) {
                return '<a href="users/' . $user->id . '/delete" class="btn btn-danger btn-xs">Delete</a>';
            });
return $datatables->make(true);
```

In the stack trace the error itself occurs on the editColumn but commenting the addColumn named 'delete' fixes the error entirely, so I believe that is the root cause. There is nothing in my code anywhere that should result in data being deleted. 

Following a stack trace so it appears to be some error in compileContent() or getMixedValue()
![chrome_2016-07-13_18-48-43](https://cloud.githubusercontent.com/assets/11610991/16811858/a541de8e-492a-11e6-9d4b-d400be697cb9.png)

**Comment by yajra** [comment] 2016-07-14 00:12
@ctoma thanks for reporting. Duplicate of #565. Will take a second look on this issue, the last time I checked, it works fine for me.

**Comment by yajra** [comment] 2016-07-14 00:13
BTW, if you can, please submit a PR. Thanks!

**Closed by yajra** 2016-07-14 00:12 UTC
