### ISSUE TITLE
Global Search Issue in your latest version of file

### ISSUE THREAD

**Issue by ashutoshjha88** [yajra/laravel-datatables#77] opened 2015-06-16 07:05 UTC
In BaseEngine.php line no. 316 u missed ! sign

```php

 if (!$this->isColumnSearchable($columns, $i, false)) {
                    continue;
                }

**Comment by yajra** [comment] 2015-06-16 07:05
@ashutoshjha88 thanks for reporting. duplicate of #56 and was fixed

**Closed** 2015-06-16 07:06 UTC
