### ISSUE TITLE
Reponsive table problem

### ISSUE THREAD

**Issue by SeptuagintMK** [yajra/laravel-datatables#642] opened 2016-07-14 03:57 UTC
### Summary of problem or feature request

Grretings, i have a problem with the table, a solution for [this](https://gyazo.com/d2107887e9c69e85b4e89ab922821a4a) and [this](https://gyazo.com/ee6cd84e46c95631cc7b01c31119e72a)

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment] 2016-07-14 04:27
Try using https://datatables.net/extensions/responsive/

**Comment by SeptuagintMK** [comment] 2016-07-14 04:35
I will have to add [this](https://gyazo.com/6c90322a5f23af84d24d0540156dc752) in my project, right?

**Comment by SeptuagintMK** [comment] 2016-07-14 05:17
It works with normal Datatables, but it doesn't work with the plugin of bootstrap datatable

**Comment by yajra** [comment] 2016-07-14 05:27
Duplicate of https://github.com/yajra/laravel-datatables/issues/526. See that issue for ref.

**Closed by yajra** 2016-07-14 05:27 UTC
