### ISSUE TITLE
Filter/search within nested relations

### ISSUE THREAD

**Issue by Morinohtar** [yajra/laravel-datatables#696] opened 2016-08-17 17:11 UTC
Hello,

The problem i'm having regards nested relations and trying to filter results through them.
Below is part of the code of the function that is called via ajax to populate da datatable; and the javascript columns details of the datatable.
Everything works fine, even filtering through the "user" relation, ie, i can filter by the email field. But when i try to filter by the "user.roles" relation it doesnt give any output, it cant find anything.
I used to have this code done using joins, but im trying to avoid that.
Hope i was explicit enough, if not, please tell me :P

Thanks
### controller function, called via ajax

``` php
public function indexAjax(Request $request)
{
        $administrators = \App\Models\Administrator::with(['user', 'user.roles'])->select(DB::raw('CONCAT(CONCAT(administrators.first_name, " "), administrators.last_name) AS fullname, administrators.*'))->get();

        return Datatables::of($administrators)
            ->editColumn('user.roles.display_name', function ($administrator) {
                return $administrator->user->roles()->first()->display_name;
            })
            ->make(true);
}
```
### this little part belongs to the javascript of the datatable

``` javascript
columns: [
                    {data: 'select_administrator', name: 'select_administrator', orderable: false, searchable: false},
                    {data: 'id', name: 'id'},
                    {data: 'fullname', name: 'fullname'},
                    {data: 'user.email', name: 'user.email'},
                    {data: 'user.roles.display_name', name: 'user.roles.display_name'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'actions', name: 'actions', orderable: false, searchable: false}
                ],
```

**Comment by yajra** [comment] 2016-08-23 06:05
@Morinohtar not yet sure if nested relationship is supported by the package. Haven't tried it yet. I suggest you do join statements atm if possible for a more stable solution.

**Comment by yajra** [comment] 2016-08-26 01:35
@Morinohtar can you try v6.18.0 if it fixes this issue? Just realized that is likely the same as #698

**Comment by yajra** [comment] 2016-08-28 05:27
Should be fixed on v6.18.0 as confirmed on #698.

**Comment by ethaizone** [comment] 2016-11-18 06:13
Can we reopen this one? This one is not same as issue #698. This is about nested relations.
This feature can use join to make temporary solution to solve it.

**Comment by Morinohtar** [comment] 2016-11-18 09:00
I'm sorry, but i havent tested yet. If this is already working then great :)

**Comment by ethaizone** [comment] 2016-11-18 09:24
@Morinohtar Currently. It's not work. XD
I just created pull request #841 and wait to test.

**Comment by yajra** [comment] 2016-11-19 07:59
Should be fixed on v6.22.0. Thanks!

**Closed by yajra** 2016-11-19 07:59 UTC
Labels: bug, enhancement

**Comment by bdteo** [comment] 2018-03-21 23:54
Using `Datatables::of(Model::with('relation')->get())` works. However, `Datatables::of(Model::with('relation'))` does not work.

I see the following code in version 8

```
protected function compileQuerySearch($query, $columnName, $keyword, $boolean = 'or')
    {
        $parts    = explode('.', $columnName);
        $column   = array_pop($parts);
        $relation = implode('.', $parts);
        if ($this->isNotEagerLoaded($relation)) {
            return parent::compileQuerySearch($query, $columnName, $keyword, $boolean);
        }
        $query->{$boolean . 'WhereHas'}($relation, function (Builder $query) use ($column, $keyword) {
            parent::compileQuerySearch($query, $column, $keyword, '');
        });
    }
```
It seems version 6 lacks support for searching through relations. It constructs queries like these "and LOWER(`seminar_date`.`seminar`.`title`)".

**Can you confirm there is no support for relationship searches as of version 6 ?**

**Is there any possibility that you port this feature to version 6 ?**

At this point using version 8 is not an option since it's not compatible with Laravel 5.1.

**Comment by ridaamirini** [comment] 2018-12-29 04:32
@yajra Any update ?

**Comment by yajra** [comment] 2019-01-03 01:03
Relation is working afaik. Can you provide the errors you received? Also, you need to include select when using relation. `Model::with('relation')->select('models.*')`

**Comment by yajra** [comment] 2019-01-03 04:20
`languages.name` not found sql error. Is that a valid column? Make sure you have the proper column name defined on your js. See https://datatables.yajrabox.com/eloquent/relationships for ref.

**Comment by ridaamirini** [comment] 2019-01-03 06:42
@yajra Ok i found it was my fault. The right name was `language.translations.name`.

**Comment by Nasirkhan-259** [comment] 2022-02-03 11:28
let suppose i want to filter sale report which is linked with store and inside store there is a **column** called **area** 
$eloquentData->whereHas("stores", function ($query) use ($request) {
                    $query->where("area", "like", "%" . $request->area . "%");
                });
