### ISSUE TITLE
Invalid Parameter Number with WHERE clause

### ISSUE THREAD

**Issue by waiylgeek** [yajra/laravel-datatables#652] opened 2016-07-20 03:15 UTC
### Invalid Parameter Number

```
$rows = myTable::select(['a', 'b', 'c']);

return Datatables::of($rows)
  ->add_column('a', '{!! $a !!}', 0)
  ->add_column('b', function($d){
        $data = anotherTable::where('col1', 1)->where('col2', 2)->first();
       return $data->anotherCol;  
  }, 1)
  ->add_column('d', '{!! $d !!}', 2)
  ->make(true);
```
It throws the following error:
```
SQLSTATE[HY093]: Invalid parameter number (SQL: select `anotherTable`.`col1`, `anotherTable`.`col2` from `anotherTable` where `anotherTable`.`col1` = 1 and `anotherTable`.`col2` = ? )
```
As you can see it does not take the value of the last `WHERE clause`, it returns `?`, I tried with only one `WHERE clause` and with more than 2 `WHERE clauses` and it still ignoring the value of the last `WHERE clause`
### System details

- Operating System: Linux/Ubuntu 16.04 LTS
- PHP Version 5.6.*
- Laravel Version 5.2
- Laravel-Datatables Version ~6.0

**Comment by yajra** [comment] 2016-07-22 04:29
Duplicate of #651.

**Closed by yajra** 2016-07-22 04:29 UTC
Labels: duplicate
