### ISSUE TITLE
Html not interpreted

### ISSUE THREAD

**Issue by lk77** [yajra/laravel-datatables#1065] opened 2017-03-14 14:28 UTC
Hello,

i don't know if it's a bug or if it's intended.
i have an action column inside my datatables, with a bunch of <a> elements.
in v6.24.1 it works but in v7.3.0 it doesn't work anymore, it shows plain html.
I suppose that my code is escaped somewhere, but i dont find where.

here is my code 

```
return Datatables::of($clips)
            ->addColumn('action', function ($clip)
        {
            return view('client.clip._action', compact('clip'));
        })->make();
```

```
<a href="{{ url('/client/clip/' . $clip->id) }}" class="btn btn-success btn-xs" title="View clip"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"/></a>
<a href="{{ url('/client/clip/' . $clip->id. '/edit') }}" class="btn btn-primary btn-xs" title="Edit clip"><span class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
```

thanks

**Comment by yajra** [comment] 2017-03-15 00:58
Duplicate of #1031. Use `rawColumns`. Thanks!

**Closed by yajra** 2017-03-15 00:58 UTC
Labels: question

**Comment by joanebrown** [comment] 2017-04-18 10:31
Hi yajra,

I trying to use `rawColumns` but doesn't work:

    return Datatables::of($objects)
        ->addColumn('edit', function($object) {
            return '<a href="myroute"><button class="btn btn-sm">edit </button></a>';
        })
        ->editColumn('active', function($object) {
               if ($object->active) {
                   return '<span class="label label-sm label-success">active</span>';
               }
               return '<span class="label label-sm label-danger">inactive</span>';
    })
    ->rawColumns(['active', 'edit', 'name'])
    ->make();

When I use `->escapeColumns([])` works well, but for all the columns and I want this only for three columns. I tried with `->escapeColumns(['active', 'edit', 'name'])` but doesn't work either.

there is any way to do what i need?

thank you for your amazing workd :))
