### ISSUE TITLE
v7 - Class 'Yajra\Datatables\Services\DataTable' not found

### ISSUE THREAD

**Issue by aborigines** [yajra/laravel-datatables#986] opened 2017-02-07 15:13 UTC
v7 - Class 'Yajra\Datatables\Services\DataTable' not found

How to solve it ?

Thank you.

**Comment by yajra** [comment] 2017-02-07 15:38
See [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) please. Thanks!

**Comment by aborigines** [comment] 2017-02-07 16:19
im implement class as a service as like v.6 , on source code v.7 i don't see a service .

ref. https://datatables.yajrabox.com/service

**Comment by yajra** [comment] 2017-02-08 00:24
Have you seen the upgrade guide? You need to install `laravel-datatables-buttons` plugin to use it on v7. Duplicate of #980. Thanks!

**Closed by yajra** 2017-02-08 00:24 UTC
Labels: documentation, duplicate, question

**Comment by MATOVURONALD** [comment] 2017-09-14 16:16
FatalThrowableError in ProviderRepository.php line 208:
Class 'Yajra\Datatables\DatatablesServiceProvider' not found
i have checked the upgrade guide and installed the yajra package but it cannot find the datatable service provider

**Comment by yajra** [comment] 2017-09-15 00:48
@MATOVURONALD namespace were updated from`Datatables` to `DataTables`. You are still using the older version.

**Comment by andrefrd** [comment] 2017-12-20 13:04
I only got it working without the service provider class.

Removing the line "Yajra\DataTables\DataTablesServiceProvider::class" from config/app.php

**Comment by vahidalvandi** [comment] 2018-11-25 05:58
show in v8.4

`Class 'Yajra\Datatables\Services\DataTable' not found
`
