### ISSUE TITLE
Can this be used with DataTables Search Panes

### ISSUE THREAD

**Issue by einkinder** [yajra/laravel-datatables#2471] opened 2020-09-27 20:29 UTC
### Summary of problem or feature request

I would like to incorporate DataTables Search Panes but I am not seeing how to add.
https://datatables.net/extensions/searchpanes/examples/

- Operating System
- PHP Version 7.4
- Laravel Version 8 
- Laravel-Datatables Version latest

**Comment by yajra** [comment] 2020-10-01 07:13
Duplicate of https://github.com/yajra/laravel-datatables/issues/2463.

**Closed by yajra** 2020-10-01 07:13 UTC
Labels: Search Panes
