### ISSUE TITLE
Database with 5000 rows

### ISSUE THREAD

**Issue by helderalvesoliveira** [yajra/laravel-datatables#1056] opened 2017-03-09 11:37 UTC
Hello, 
my database has 5000 and datatables server side is to slow. 
How can fetch (new select) my table only 100 rows every time when click on pagination datatables? 

Thanks very much.

**Comment by yajra** [comment] 2017-03-09 13:13
Possible duplicate of #1053. See it for ref.

**Closed** 2017-03-15 00:59 UTC
Labels: duplicate, question
