### ISSUE TITLE
Global search doesn't add wildcards to relationships

### ISSUE THREAD

**Issue by JanKyselica** [yajra/laravel-datatables#710] opened 2016-08-24 09:36 UTC
### Summary of problem

I have model City with relationship type of belongsTo to the Region model. I use datatables for viewing all cities. When I type keyword to global search input I'm getting this SQL in debug:

```sql
select `chk_cities`.* from `chk_cities` 
    left join `chk_regions` on `chk_cities`.`region_id` = `chk_regions`.`id` 
    where (LOWER(`chk_cities`.`id`) LIKE '%slovensko%' 
         or LOWER(`chk_cities`.`name`) LIKE '%slovensko%' 
         or LOWER(`chk_cities`.`display_name`) LIKE '%slovensko%' 
         or (select count(1) from `chk_regions` where `chk_cities`.`region_id` = `chk_regions`.`id` and LOWER(`display_name`) LIKE 'Slovensko' and `chk_regions`.`deleted_at` is null) >= 1 
         or LOWER(`chk_cities`.`order`) LIKE '%slovensko%' 
         or LOWER(`chk_cities`.`hidden`) LIKE '%slovensko%') 
         and `chk_cities`.`deleted_at` is null order by `chk_regions`.`display_name` asc limit 75 offset 0
```
As you can see, in city columns are used wildcards, but wildcards aren't used in regions column.

Controller:
```php
public function datatable(Request $request)	
	{
		$cities = City::with('region')->select(['cities.*']);
		return $this->getDatatable($cities)->make(true);
	}
```

### System details

- Operating System - Ubuntu 16.04
- PHP Version - PHP 7.0.9-1
- Laravel Version - Laravel Framework version 5.2.43
- Laravel-Datatables Version - "yajra/laravel-datatables-oracle": "^6.11",
- Datatables - 1.10.12

**Comment by yajra** [comment] 2016-08-24 09:49
Thanks for reporting! This is bug and duplicate of https://github.com/yajra/laravel-datatables/issues/698

**Closed by yajra** 2016-08-24 09:49 UTC
