### ISSUE TITLE
Call to undefined Method Illuminate\Database\Query\Builder::getForeignKey() 

### ISSUE THREAD

**Issue by arnoldjp57** [yajra/laravel-datatables#946] opened 2017-01-26 09:02 UTC
datatables server side throws the above error after upgrade to Laravel 5.4

Controller .....
```
$visis = Visi::where('prac',get_curr_prac())
 ->with(['visi_patn','visi_vsta','visi_dept'])
  ->select('visis.*', 'visis.id as visisID');
      return Datatables::of($visis)->make(true);
```
Model .... (Visi)
```
public function visi_patn()
  {
    return $this->hasOne('App\Patn','id','patn');
  }
```

- Operating System   UBUNTU 16.04
- PHP Version   7.1
- Laravel Version  5.4
- Laravel-Datatables Version 6.24

**Comment by yajra** [comment] 2017-01-26 13:18
Duplicate of #943, Laravel 5.4 will be supported once v7 is released. Thanks!

**Closed by yajra** 2017-01-26 13:18 UTC
Labels: duplicate

**Comment by arnoldjp57** [comment] 2017-01-26 13:20
Great, Thanks .....
