### ISSUE TITLE
How to use bootstrap 4 version in 10.x?

### ISSUE THREAD

**Issue by AndriiTereshchuk** [yajra/laravel-datatables#2952] opened 2023-02-16 23:23 UTC
Or are you only using version 5?

**Comment by yajra** [comment] 2023-02-19 13:33
Haven't tried Laravel 10 with BS4, but it should be the same. Just change the packages to bs4 versions. See https://github.com/yajra/laravel-datatables-vite for ref.

**Comment by yajra** [comment] 2023-02-19 14:12
Duplicate of https://github.com/yajra/laravel-datatables-vite/issues/4#event-8504507837

**Closed by yajra** 2023-02-19 14:12 UTC
Labels: question
