### ISSUE TITLE
Open button doesn't show with table with details 

### ISSUE THREAD

**Issue by e11en** [yajra/laravel-datatables#153] opened 2015-08-26 11:44 UTC
I've got this weird thing and I can't find the solution here or other places so I hope you could help me.
I followed your instructions in the demo app and everything is working perfectly except for one tiny thing.

The icon of the green sphere with plus sign is not visible and instead the text [object Object] is displayed in every row. The red sphere is however working..

![screenshot from 2015-08-26 13 36 26](https://cloud.githubusercontent.com/assets/855939/9492506/882dc1d0-4bf8-11e5-8007-103c036c785d.png)

**Comment by e11en** [comment] 2015-08-26 13:13
UPDATE:
So I found out that it has to do with the data that is being send to this column, it renders the null as an object. still haven't found a solution though.
![screenshot from 2015-08-26 15 10 38](https://cloud.githubusercontent.com/assets/855939/9494203/09341f98-4c05-11e5-818c-52b13ac7b656.png)

**Comment by yajra** [comment] 2015-08-26 13:48
can you paste your controller snippet? It seems like its rendering an object from your controller ajax response.

**Comment by e11en** [comment] 2015-08-27 09:24
Sure, is this the part that you need?

    public function getIndex()
    {
        return view('brand.index');
    }

    public function anyData()
    {
        $brands = Brand::join('lstCountry', 'tblBrand.braCountryId', '=', 'lstCountry.couId')
            ->select('braId','braName','braCompanyName','couIso','braUrlSite','braUrlShop',
                'braStreet','braNumber','braSuffix','braCity','braZipCode', 'couName',
                'braPhoneNumber', 'braEmail');

        return Datatables::of($brands)
            ->addColumn('lnkSpecs', '') 
            ->addColumn('modules', $this->getModules('{{$braId}}')
            ->make(true);
    }

**Comment by yajra** [comment] 2015-08-28 13:34
@e11en, thanks for the snippet. Your controller seems fine and I can't find any issue on it. How about removing the data attribute? This is just a wild guess. This may be a javascript issue and you may have to debug it using chrome dev tools or firebug, etc….

**Comment by e11en** [comment] 2015-08-28 14:15
If gives this error but the text is gone, but the red icon isn't visible anymore as well.

![screenshot from 2015-08-28 16 12 15](https://cloud.githubusercontent.com/assets/855939/9548258/ce049898-4d9f-11e5-9cf3-e5852ac76e85.png)

**Comment by yajra** [comment] 2015-08-29 06:55
@e11en, sad to say, but I can't reproduce this issue. http://datatables.yajrabox.com/eloquent/row-details demo is working fine. Btw, what version of datatables.js are you using? Maybe try using the latest released v1.10.8?

**Comment by yajra** [comment] 2015-08-29 08:22
@e11en, FYI: I just added a [mater-details table](http://datatables.yajrabox.com/eloquent/master) demo and I used the details-control too. Did not encounter same issue as you have. :(

**Comment by e11en** [comment] 2015-08-31 11:51
I'll try the redo the complete process maybe that will work thanks for the help anyway!

**Comment by yajra** [comment] 2015-09-13 23:42
Closing due to can't reproduce the error. Sorry for the inconvenience. 

One final note, please make sure that you have the proper DT js and css version. Just remembered someone having an odd issue and it was due to conflicting js and css version that he was using.

**Closed by yajra** 2015-09-13 23:42 UTC
