### ISSUE TITLE
how to use this in vue.js

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#1632] opened 2018-02-18 10:00 UTC
@yajra ,

can I ask some help how to use in vue.js ?

index.blade

```
   <div class="row" id="app">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"><a href="{{ route('credit.create') }}" type="button" class="btn btn-block btn-success btn-flat">Create</a></h3>
                </div>
                <div class="table-responsive box-body">

                    <table width="100%" class="table table-bordered table-striped" id="my-table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th width="20%;"></th>
                        </tr>
                        </thead>

                    </table>

                </div>
            </div>
        </div>

    </div>

```

this is my getdata.js
```
new Vue({
    el:'#app',
    created: function () {
        var mytable= $('#my-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: 'getdata',
            columns: [
                {data: 'particulars', name: 'particulars'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });

    }
});


```

**Comment by yajra** [comment] 2018-03-11 02:50
I tried to play with my custom vue data-table script again. Try using the [gist](https://gist.github.com/yajra/ff9218f58fc2d1499e7ce3d356549d24) I created as a ref.

Duplicate of #1607 

Thanks!

**Comment by Bolhy10** [comment] 2018-04-16 09:51
@yajra I have an action button in my controller to eliminate what happened to the table, it is shown and everything, my question is how do I do it for when I click with function @click de vue, js work.

**Comment by antoniodesa** [comment] 2018-09-27 16:37
Did you found a solution to @click?

**Comment by Bolhy10** [comment] 2018-09-27 23:44
No, I have found the solution

**Comment by Ubaidullah92** [comment] 2019-01-27 17:40
any one found a solution to v-on:click?

**Comment by arangel3tech** [comment] 2019-03-25 16:38
v-on:click not solution?

**Comment by noogen** [comment] 2019-04-08 19:58
Shameless plug, I wrote this datatables.net vue wrapper component: https://github.com/niiknow/vue-datatables-net 

I'm also using with yajra/laravel-datatables for server-side response.

**Comment by mdsagor07** [comment] 2022-01-26 07:03
> @yajra any one found a solution to v-on:click? it is not working 

created(){
      //this.allEmployee();
     
      $(document).ready( function () {

    
           // $.noConflict();
            $('#myTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "api/employee",
               
                "columns": [
              
                {data: 'name', name: 'name'},   
                 { data: 'photo', name: 'photo',
                    render: function( data, type, full, meta ) {
                        return "<img src=\"" + data + "\" height=\"45\"/>";
                    }
                },   
                {data: 'email', name: 'email'},
                {data: 'phone', name: 'phone'},
                {data: 'salary', name: 'salary'},
                {data: 'joining_date', name: 'joining_date'},
               
                  {
              data: 'id',name: 'action',
              render: function(data){
                let btn; 
                  
                
                         btn='<router-link :to="{name: edit-employee, params:{id:'+data+'}}" class="btn btn-sm btn-primary">Edit</router-link>';
                         btn= btn+ ' <button  id=".btn-delete" onclick="draw()"  class="edit btn btn-danger btn-sm m-2">Delete</button>';
                        return btn;
                        
                        
             },
             
          },

          

                    
                ]
            });

            
   });

**Comment by bkens** [comment] 2023-02-06 08:25
Hello, @Bolhy10. Did you get answer for this question please?

**Comment by yajra** [comment] 2023-02-07 01:14
See https://datatables.net/blog/2022-06-22-vue. I was not able to use VueJS further with DataTables so I may not be able to answer this accurately. I think we should redirect the questions to the [official package](https://github.com/DataTables/Vue#readme).

Closing this issue since it's also out of the project scope. Thanks!

**Closed by yajra** 2023-02-07 01:14 UTC
Labels: question
