### ISSUE TITLE
yajra all in one packge error in larave 9 #2746

### ISSUE THREAD

**Issue by zainawan99** [yajra/laravel-datatables#2764] opened 2022-03-23 09:04 UTC
### Summary of problem or feature request

![image](https://user-images.githubusercontent.com/24542584/159662243-c45dc7f0-8284-4f37-a623-8a53aba8f265.png)

### System details

- Operating System
- PHP Version 8.0.2
- Laravel Version 9.5.1
- Laravel-Datatables Version 1.5

**Comment by schonhoff** [comment] 2022-03-24 21:17
Hello,

Laravel 9 allows psr/simple-cache to use version 1-3. Because of that a fresh Laravel installation will lock the version to 3. So you need to downgrade the version manually or with the parameter, I would guess. The problem is that Laravel-Excel (in your screenshot known as maatwebsite/excel is using phpoffice/phpspreadsheet under the hood. They are currently only support version 2 or 3 of the psr/simple-cache package. Your php version is supported after maatwebsite/excel version 3.1.26 and your Laravel version after version 3.1.36

maybe this will help:
https://github.com/yajra/laravel-datatables/issues/2746#issuecomment-1075358110

You can try to use ```-with-all-dependencies``` as a parameter for the install command.

Or you can wait for the Laravel 9 Support end of this month (hopefully)
https://github.com/yajra/laravel-datatables-buttons/issues/143
(the last comment should help a lot)

**Comment by yajra** [comment] 2022-07-02 04:02
Should be fixed on v10 too. Thanks!

**Closed by yajra** 2022-07-02 04:02 UTC
