### ISSUE TITLE
Display Checkbox not working

### ISSUE THREAD

**Issue by fatoni69** [yajra/laravel-datatables#1072] opened 2017-03-18 04:57 UTC
![Image](https://4.bp.blogspot.com/-uVZKAayNVZ8/WMy83LVpFJI/AAAAAAAABvs/VtoUR8oC_FwAkKXDDK6ix6wv4VKnhUo8QCLcB/s700/Screenshot.png)

### HTML
```html
<table id="mahasiswa" class="table table-striped">
    <thead>
        <tr>
            <th><i class="glyphicon glyphicon-th"></i></th>
            <th>Nim</th>
            <th>Nama</th>
            <th>Tempat Lahir</th>
            <th>Tanggal Lahir</th>
            <th>Alamat</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
</table>
```
### Script Js
```js
$(function() {
    var table = $("#mahasiswa").DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ url('data') }}",
        columns: [
          { data: 'checkmark' },
          { data: 'nim' },
          { data: 'nama' },
          { data: 'tempat_lahir' },
          { data: 'tanggal_lahir' },
          { data: 'alamat' },
          { data: 'email' },
          { data: 'action', 'searchable': false, 'orderable':false }
       ]
    });
});
```

### MahasiswaController.php

```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
 
use App\Http\Requests;
use App\Mahasiswa;
use Yajra\Datatables\Facades\Datatables;

class MahasiswaController extends Controller
{
    public function index()
    {
        return view('mahasiswa');
    }
 
    public function data(Request $request)
    {
        // cek ajax request   
        if($request->ajax()){
            $mahasiswa = Mahasiswa::select('nim', 'nama', 'tempat_lahir', 'tanggal_lahir', 'alamat', 'email')
                        ->get();
            // return Datatables::eloquent(Mahasiswa::query())
            return Datatables::of($mahasiswa)
            ->addColumn('checkmark', '<input type="checkbox" name="" value"">')
            ->addColumn('action', 
			'<a href="#" title="Edit" class="btn-sm btn-warning"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>

			<form style="display: inline">
			    <input name="_method" type="hidden" value="DELETE">
			    <input name="_token" type="hidden" value="{!! csrf_token() !!}">
			    <button class="btn-sm btn-danger" type="button" style="border: none"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
			</form>')
            ->make(true);

        } else {
            exit("Not an AJAX request -_-");
        }
    }
}

```
I'm using:
- Laravel Version 5.4
- Laravel-Datatables Version 7.0

How to fix it ?

**Comment by yajra** [comment] 2017-03-18 06:03
Duplicate of #1031. Thanks!

**Closed by yajra** 2017-03-18 06:03 UTC
