### ISSUE TITLE
give me an email .upload some images 

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables#273] opened 2015-12-02 01:12 UTC
github cannot upload images easy,or you send an email to me(36903631@qq.com)

**Comment by yajra** [comment] 2015-12-02 02:21
Please send your pull request so I can review. Seems like a duplicate of #272. Thanks!

**Comment by openvast** [comment] 2015-12-02 02:26
i found to bug. 1: leftjoin,2:select table.column as mycolumn,
i try to send pull request

**Comment by openvast** [comment] 2015-12-02 02:47
![searchcolumn](https://cloud.githubusercontent.com/assets/9793122/11520813/cb294aa0-98e1-11e5-852a-2c8fe33dc6c3.png)
I can use search one colum  ,i try to do。。。

**Comment by yajra** [comment] 2015-12-02 06:03
Fix on v5.12.2. Thanks!

**Closed by yajra** 2015-12-02 06:03 UTC
