### ISSUE TITLE
how to clear state from back-end in yajra? 

### ISSUE THREAD

**Issue by moathOSA** [yajra/laravel-datatables#2882] opened 2022-10-18 13:19 UTC
how can i reset saved state for pacific table from laravel side in yajra ? 

PHP Version ^8.0.0
Laravel Version ^9.0.0

**Comment by yajra** [comment] 2022-11-03 00:51
Duplicate of https://github.com/yajra/laravel-datatables/issues/2883

**Closed by yajra** 2022-11-03 00:51 UTC
Labels: duplicate
