### ISSUE TITLE
datatable collection on search getting a error - mb_strtolower() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by webassic15** [yajra/laravel-datatables#921] opened 2017-01-12 13:26 UTC
@yajra 
JQuery code : 

`<script>
    var otable;
    $(document).ready(function () {
        $('#opacitylow').css({'opacity': 0.5});
        $('.loader').css({'opacity': 2.0});
        overlay = $('<div></div>').prependTo('body').attr('id', 'overlay');
        
        otable = $('#project-list').DataTable({
            processing: true,
            serverSide: true,
            ajax: '/getData',
            columns: [
                {data: 'project_view_id', name: 'project_view_id'},
                {data: 'project_name.name', name: 'project_name.name'},
                {data: 'client.name', name: 'client.name'},
                {data: 'client_country.name', name: 'client_country.name'},
                {data: 'account_mgr', name: 'account_mgr'},
                {data: 'project_mgr', name: 'project_mgr'},
                {data: 'project_coordinator', name: 'project_coordinator'},
                {data: 'start_date', name: 'start_date'},
                {data: 'consultant_count', name: 'consultant_count'},
                {data: 'status', name: 'status'}
            ],
            "columnDefs": [
                {
                    "targets": [9],
                    "visible": false
                }
            ],
            fnInitComplete: function () {
                $('#opacitylow').css({'opacity': 2.0});
                $('.loader').css({'opacity': 0.5});
                overlay.remove();
            }
        });
        $('#listing_data').delegate('#listing_status', 'change', function () {
            otable.columns(9).search(this.value).draw();
        });
    });
</script>`

On reload page, all is working fine but when i try to search any value then getting a error as below : 

ErrorException in Str.php line 171:
mb_strtolower() expects parameter 1 to be string, array given

**Comment by yajra** [comment] 2017-01-20 12:03
Duplicate of #932 Thanks!

**Closed by yajra** 2017-01-20 12:03 UTC
Labels: duplicate
